baseURL = 'https://luis-javier-gonzalez-alonso.github.io/grumpy-okapi/'
languageCode = 'en-GB'
title = '/ˈtɛknɪkəl ˈraɪtɪŋ/'
theme = 'hermit'

pygmentsCodeFences = true
pygmentsUseClasses = true

rssLimit = 10  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/

[author]
  name = "Luis J. González"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#494f5c"
  homeSubtitle = "Notes for myself and whoever may find them useful"
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

  relatedPosts = false  # Add a related content section to all single posts page
  code_copy_button = true

  [[params.social]]
    name = "github"
    url = "https://github.com/luis-javier-gonzalez-alonso"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/luis-javier-gonz%C3%A1lez-22a201189/"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10
