name: Build statics

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clean public folder
        run: rm -rf public/*
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build statics
        run: hugo --minify
      
      - name: Deploy
        run: cd public && git add . && git commit -m "- Updates site" && git push
