name: Build statics

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Clean
        run: rm -rf public/*
        
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build
        run: hugo --minify
      
      - name: Deploy
        uses: github-actions-x/commit@v2.9
        with:
          github-token:  ${{ secrets.CI_PAT }}
          commit-message: "- Updates site"
          email: ci@actions.github.com
          name: ci
