name: Build statics

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_PAT }}
          submodules: recursive

      - name: Clean
        run: rm -rf public/*
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
      - name: Build
        run: hugo --minify

      - name: Push submodules
        run: |
          git config --global user.name ci
          git config --global user.email 'ci@actions.github.com'
          pushd public && git add . && git commit -am "- Updates site" && git push && popd
