name: hugo-pages-deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          clean: true

      - uses: peaceiris/actions-hugo@v2
      - uses: sterlingwes/gh-pages-deploy-action@v1.1
        with:
          access-token: ${{ secrets.CI_PAT }}
          source-directory: public
          build-command: hugo --minify
