name: hugo-pages-deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          repository: luis-javier-gonzalez-alonso/grumpy-okapi
          token: ${{ secrets.GITHUB_TOKEN }}
          ssh-strict: true
          persist-credentials: true
          clean: true
          fetch-depth: 1
          lfs: false
          set-safe-directory: true
      
      - name: Clean up
        run: rm -rf public/ && mkdir -p public
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
      - name: Build
        run: hugo --minify

      - uses: actions/upload-pages-artifact@v0
        with:
          path: public
          retention-days: 1
          
      - run: |
          tar --dereference --hard-dereference  -C public -cvf /home/runner/work/_temp/artifact.tar .

      - uses: actions/upload-artifact@main
        with:
          name: github-pages
          path: /home/runner/work/_temp/artifact.tar
          retention-days: 1
          if-no-files-found: warn

  deploy-build-status:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v1
        with:
          emit_telemetry: true
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v1
        with:
          emit_telemetry: false
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
