name: hugo-pages-deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          clean: true

      - uses: peaceiris/actions-hugo@v2
      - run: git worktree add public gh-pages
      - name: Build Hugo site
        run: hugo --minify --cleanDestinationDir

      - name: Deploy to gh-pages branch
        run: |
          cd public
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if [ "`git status -s`" ]
          then
            git add --all
            git commit -am "- Updates site"
            git push --all
          fi
